[HOLD for question] define DigitalObject#==, let it be used implicitly in test comparisons
sul-dlss/pre-assembly pull request #1008
Opened 2022-06-18 00:33 UTC by jmartin-sul

## Why was this change made? 🤔

* pro: this makes the tests more concise and adds a possibly useful equality checking method
* con: i'm not sure that this is actually captures the desired semantics of `DigitalObject#==`.  also, only the tests use it at present.  i think the comparison works for the tests, but for example, should it rely on the default instance-equivalence equality check for `Batch`, or should `Batch` be compared for semantic equality between possibly different instances instead?

## How was this change tested? 🤨

unit tests

⚡ ⚠ If this change has cross service impact (e.g. changes what is written to shared file systems or how it uses APIs), ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

2022-06-21 23:21 UTC, ndushay commented
@jmartin-sul who o you believe can answer this question?  Should it be a post standup topic?

2022-06-23 17:45 UTC, ndushay requested changes
would want method in spec_helper if it's only used for tests.

2022-06-23 18:27 UTC, peetucket commented
Created spec_helper method and used in the tests.  Removed equals method in digital object class.

2022-06-23 22:02 UTC, ndushay approved these changes

2022-06-23 22:18 UTC, peetucket commented on spec/spec_helper.rb
> +def objects_equivalent?(objects1, objects2)
renamed the method

2022-06-23 22:19 UTC, merged

2022-06-24 00:50 UTC, jmartin-sul commented
thanks @peetucket!