[wip] Update structural from Argo style file manifest if present
sul-dlss/pre-assembly pull request #1049
Opened 2022-07-18 22:34 UTC by jcoyne

## Why was this change made? 🤔

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact (e.g. changes what is written to shared file systems or how it uses APIs), ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

2022-07-20 22:26 UTC, aaron-collier requested changes
@jcoyne I'm adding "HOLD" to the label here as the linked ticket is "Hold for PR review". 

Once @andrewjbtw is back and can test, feel free to remove HOLD. Or remove now if this has been tested/approved.

2022-08-04 23:52 UTC, andrewjbtw commented
Already mentioned on Slack, but approving here too.

2022-08-05 15:45 UTC, ndushay approved these changes
Does @andrewjbtw need to notify users before this is deployed?  (meaning:  merged)

Also a comment for your consideration.

2022-08-05 15:45 UTC, ndushay commented on app/lib/pre_assembly/file_manifest.rb
> +        folder_name = folder(row)
yay for better variable names

2022-08-05 15:45 UTC, ndushay commented on app/lib/pre_assembly/file_manifest.rb
> +    def folder(row)
would it make more sense to call this method `folder_name` ?

2022-08-05 15:45 UTC, ndushay commented on app/services/object_file_validator.rb
> +    file_manifest.present?
👍🏻

2022-08-05 16:22 UTC, andrewjbtw commented
@ndushay 's comments make me realize that I forgot to ask if merging this means the preassembly style of file manifest will no longer be supported. If that's the case, I need to do a follow up ticket to make some fields optional before this can be deployed.

2022-11-07 18:05 UTC, peetucket commented
@andrewjbtw & @jcoyne -- can we move this forward and merge or is there still some communication/testing to be done?

Justin: looks like a super small merge conflict that will be easy to fix with a rebase, not sure if you want us to do it as needed.

2022-11-07 18:09 UTC, andrewjbtw commented
I still have the question I had above: does this completely replace the current preassembly file manifest structure? Or will you be able to submit either format? 

If it replaces the current format, that would be ok, except I would have some additional tickets. When I tested it, everything worked if you submitted data for every column but not if you submitted only the data users usually put on the current manifest. I can specify which columns should be required and which not.

Since the preassembly-focused workcycle was over by the time I returned from being out sick, I'd shelved following up on this for when there was more time in the future.

2022-11-07 18:20 UTC, peetucket commented
My reading of this PR code is that it doesn't replace the current format, and that you can use either (with the same "file_manifest.csv" filename), and it decides if it will use the new format based on the presence of a column called "rights_view".  There appear to be new tests for this new format, while leaving existing tests as is (confirming continuing support for the current format?).  But it would be good if Justin recalled this as well, as I didn't work on or review this code.

2022-11-07 20:05 UTC, jcoyne commented
I don't recall any of the details as this was 3 months ago. I had totally forgotten about this.

2023-09-05 13:09 UTC, edsu commented
I believe this can be closed since work on #1197 and #1195 is complete?

2023-09-05 14:18 UTC, closed without merging