[HOLD] allow for geo objects to be accessioned
sul-dlss/pre-assembly pull request #1403
Opened 2024-01-19 22:49 UTC by peetucket

# Why was this change made? 🤔

Fixes #1397 - add option for geo objects in pre-assembly

HOLD for PO approval

# How was this change tested? 🤨

Updates tests
But need to validate onstage with actual data

2024-01-19 22:49 UTC, peetucket commented on app/lib/pre_assembly/digital_object.rb
adjusting this comment because i don't think we are using assembly-objectfile gem anymore for this purpose

2024-01-19 22:50 UTC, peetucket commented on app/lib/pre_assembly/digital_object.rb
>        log "    - pre_assemble(#{druid.id}) finished"
previously we would always get the default workflow started in DSA, which is `assemblyWF` ... I think we now want this to depend on the content type supplied

2024-01-19 22:51 UTC, peetucket commented on app/lib/pre_assembly/from_staging_location/file_set.rb
>          when :'3d'
based on this example object: https://argo-stage.stanford.edu/view/druid:cj778hn3376

2024-01-19 22:51 UTC, peetucket commented on app/services/start_accession.rb
>      )
Allow us to tell DSA which exact workflow we want started instead of just accepting the default

2024-01-22 13:55 UTC, edsu requested changes
This looks good! A couple questions I have:

1. Usually preassembly jobs kick off assemblyWF which in turns starts accessioningWF. Do we want gisDeliveryWF to start accessionWF when it completes? 
2. The fixture data includes a data.zip and other files that are created gisAssemblyWF. I don't think it's a problem for the test since it's just files, but perhaps it's a bit confusing to read? If you want to see what the files look like beforehand take a look at some of the examples in `sul-preassembly-prod:/gis_workflow_data/fixtures/`.

2024-01-22 17:00 UTC, peetucket commented
> 1. Usually preassembly jobs kick off assemblyWF which in turns starts accessioningWF. Do we want gisDeliveryWF to start accessionWF when it completes?

Good question - need to investigate how this workflow works to see what makes sense.  I'm not sure how the current gisDeliveryWF proceeds.

> 2. The fixture data includes a data.zip and other files that are created gisAssemblyWF. I don't think it's a problem for the test since it's just files, but perhaps it's a bit confusing to read? If you want to see what the files look like beforehand take a look at some of the examples in `sul-preassembly-prod:/gis_workflow_data/fixtures/`.

Yes, i got a bit lazy with fixtures due to the way the current tests are setup to all use the same base folder for all content types (which is a bit wonky).  Using a different fixture folder for the GIS tests makes sense, will just need some more time restructuring the specs to allow for different fixture folders.

2024-01-22 18:23 UTC, peetucket commented
1. Updated the specs to use the new geo specific fixtures instead of re-using other content types.
2. My reading of [this documentation](https://consul.stanford.edu/display/SULAIRGIS/Description+of+GIS+robot+workflows) is that starting the `gisAssemblyWF` with eventually start the `assemblyWF`, which then moves the accessioning process along.  So starting `gisAssemblyWF` for a geo objects seems like the correct thing, though should be validated by the PO with some actual content.

2024-01-23 15:36 UTC, edsu commented
I don't think that documentation is up to date. We have https://github.com/sul-dlss/gis-robot-suite/issues/715 to update the workflow to start accessioning now, so it can be done separately.

2024-01-23 15:46 UTC, edsu approved these changes
I can live with the incorrect geo fixture data if it's too tedious to set up.  It would be good to see this running in Stage prior to merging.

2024-01-23 18:49 UTC, peetucket commented
I'm testing on stage now.  Considering a new integration test too.

I adjusted the tests to use geo specific specs already to avoid entangling geo files with other existing object fixtures.

2024-01-23 23:23 UTC, peetucket commented
Note: @edsu I had to make some more changes after you reviewed, not sure if you wanted to take another pass even though you approved it already.  Basically, the folder structure that is created when "staging" the content for GIS objects is a bit different, it uses "temp" instead of "content" and it doesn't want a "metadata" folder.  I based this on examining the GIS integration test data and then validated it on stage when running this branch.

2024-01-24 21:31 UTC, merged