remove references to Fedora datastream concept
sul-dlss/pre-assembly pull request #903
Opened 2022-05-09 23:31 UTC by ndushay

## Why was this change made? 🤔

Fedora3 and datastreams are no more in the SDR.  Long live the SDR!

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact (e.g. changes what is written to shared file systems or how it uses APIs), ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

2022-05-10 00:26 UTC, jcoyne requested changes

2022-05-10 00:26 UTC, jcoyne commented on app/lib/pre_assembly/digital_object.rb
> +    # @param [Object] stager the implementation of how to stage an object; a PreAssembly::CopyStager or PreAssembly::LinkStager
Can you put the list of classes where it says `[Object]` now?

2022-05-11 14:45 UTC, jcoyne requested changes

2022-05-11 19:16 UTC, ndushay commented
@jcoyne - took your suggestion - please merge at your convenience.   Sorry I got the YARD formatting wrong.

2022-05-27 16:52 UTC, jcoyne approved these changes

2022-05-27 16:52 UTC, merged