[HOLD] make all buttons blue #00548F
sul-dlss/pre-assembly pull request #931
Opened 2022-05-31 22:42 UTC by ndushay

**Holding for PO review**

## Why was this change made? 🤔

Fixes #492, which requested the button colors be changed.

## How was this change tested? 🤨

locally, unit tests, integration test, Andrew.

⚡ ⚠ If this change has cross service impact (e.g. changes what is written to shared file systems or how it uses APIs), ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

2022-05-31 22:44 UTC, justinlittman approved these changes

2022-06-01 00:15 UTC, jcoyne commented on app/assets/stylesheets/application.css
> +  background-color: #00548F;
Where did this color come from? I'm not seeing it in the identity guide. https://identity.stanford.edu/design-elements/color/accent-colors/

2022-06-01 00:17 UTC, jcoyne requested changes

2022-06-01 00:17 UTC, jcoyne commented on app/assets/stylesheets/application.css
> +  background-color: #00548F;
can you put this in a [custom property](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) called `--digital-blue-dark` and then use it here?  That makes it easier to see that it came from the branding guide at https://identity.stanford.edu/design-elements/color/web/ ?

2022-06-01 04:47 UTC, ndushay commented
@jcoyne this is going to be revisited by Astrid so it may change;  the color came from Astrid but it was 2 years ago.  Turns out there is some context that is in the ticket itself and perhaps in a slack conversation.

2022-06-08 21:50 UTC, ndushay commented
@jcoyne I just flipped this back to the original and added a comment;  I couldn't get the custom color set up properly, and this css is so far too simple to be of much concern.

2022-06-08 21:50 UTC, ndushay commented
@andrewjbtw I suspect the screenshots above are sufficient for you to sign off, but if not, let me know and I'll deploy somewhere for you.

2022-06-08 21:56 UTC, jcoyne approved these changes

2022-06-08 21:58 UTC, andrewjbtw commented
Thank you @ndushay, it looks fine.

2022-06-09 00:09 UTC, merged